config/routes.rb
Rails.application.routes.draw do
  post  '/main',      to: 'main#create_post'
  post  '/main/:id',  to: 'main#create_comment', as: 'comment'

  root 'main#index'
end

app/models/comment.rb
class Comment
  include Mongoid::Document
  
  belongs_to :post
  
  field :comment, type: String
end

app/models/post.rb
class Post
  include Mongoid::Document
  
  has_many :comments  

  field :name, type: String
  field :like, type: Integer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @posts = Post.all
  end

  def create_post
    Post.create(post_params)
    redirect_to root_path
  end

  def create_comment
    @post = Post.find(params[:id])
    @post.comments.create(comment_params)
    redirect_to root_path
  end

  private 

  def post_params
    params.require(:post).permit(:name, :like)
  end

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.haml
%h1
  Posts
- @posts.each do |post|
  %p
    Title: 
    = post.name
    %br
    Likes:
    = post.like
    .comments
      Comments
      - post.comments.each do |comment|
        %p 
          Comment: 
          = comment.comment
      = form_for :comment, url: comment_path(post.id) do |f|
        Comment
        = f.text_field :comment
        = f.submit

= form_for :post, url: main_path do |f|
  Name
  = f.text_field :name
  %br
  Like
  = f.text_field :like
  = f.submit